# Generated by Django 6.0.2 on 2026-02-06 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Piscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="ImaginePiscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immagine", models.ImageField(upload_to="immagini_piscine/")),
                ("caricata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "piscina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immagine",
                        to="pren.piscina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sdraio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etichetta", models.CharField(blank=True, default="", max_length=50)),
                (
                    "x_percentuale",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "y_percentuale",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "piscina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdrai",
                        to="pren.piscina",
                    ),
                ),
            ],
        ),
    ]
