# Generated by Django 6.0.2 on 2026-02-18 08:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Piscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("attiva", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ImmaginePiscina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immagine", models.ImageField(upload_to="immagini_piscine/")),
                ("caricata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "piscina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immagine",
                        to="pren.piscina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sdraio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etichetta", models.CharField(blank=True, default="", max_length=50)),
                (
                    "x_percentuale",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "y_percentuale",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("AI", "Rilevamento automatico"),
                            ("MANUALE", "Inserito manualmente"),
                        ],
                        default="MANUALE",
                        max_length=10,
                    ),
                ),
                (
                    "piscina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdrai",
                        to="pren.piscina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DurataDisponibile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("1H", "1 ora"),
                            ("2_3H", "2-3 ore"),
                            ("HALF", "Mezza giornata"),
                            ("FULL", "Intera giornata"),
                        ],
                        max_length=10,
                    ),
                ),
                ("attiva", models.BooleanField(default=True)),
                (
                    "piscina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durate_disponibili",
                        to="pren.piscina",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("piscina", "tipo"), name="uniq_durata_per_piscina"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_durata",
                    models.CharField(
                        choices=[
                            ("1H", "1 ora"),
                            ("2_3H", "2-3 ore"),
                            ("HALF", "Mezza giornata"),
                            ("FULL", "Intera giornata"),
                        ],
                        max_length=10,
                    ),
                ),
                ("inizio", models.DateTimeField()),
                ("fine", models.DateTimeField(editable=False)),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "piscina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prenotazioni",
                        to="pren.piscina",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prenotazioni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sdraio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prenotazioni",
                        to="pren.sdraio",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sdraio", "inizio"), name="uniq_sdraio_inizio"
                    )
                ],
            },
        ),
    ]
