# Generated by Django 6.0.2 on 2026-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pren", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duratadisponibile",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("1H", "1 ora"),
                    ("2_3H", "3 ore"),
                    ("HALF", "Mezza giornata"),
                    ("FULL", "Intera giornata"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="tipo_durata",
            field=models.CharField(
                choices=[
                    ("1H", "1 ora"),
                    ("2_3H", "3 ore"),
                    ("HALF", "Mezza giornata"),
                    ("FULL", "Intera giornata"),
                ],
                max_length=10,
            ),
        ),
    ]
