# Generated by Django 6.0.2 on 2026-02-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pren", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImaginePiscina",
            new_name="ImmaginePiscina",
        ),
    ]
