# Generated by Django 6.0.2 on 2026-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pren", "0002_rename_imaginepiscina_immaginepiscina"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdraio",
            name="origine",
            field=models.CharField(
                choices=[
                    ("AI", "Rilevamento automatico"),
                    ("MANUALE", "Inserito manualmente"),
                ],
                default="MANUALE",
                max_length=10,
            ),
        ),
    ]
