# Generated by Django 6.0.2 on 2026-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pren", "0003_sdraio_origine"),
    ]

    operations = [
        migrations.AddField(
            model_name="piscina",
            name="attiva",
            field=models.BooleanField(default=False),
        ),
    ]
